spring:
  application:
    name: oauth2-service
  cloud:
    # 使用 Nacos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8098

management:
  endpoints:
    web:
      exposure:
        include: "*"
