spring:
  application:
    name: oauth2-service-jwt
  cloud:
    # 使用 Nacos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    #数据库索引
    database: 0
    host: 124.71.187.82
    port: 6379
    password: 123456
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
        timeout: 10000

server:
  port: 8099

management:
  endpoints:
    web:
      exposure:
        include: "*"
