server:
  port: 2003

spring:
  application:
    name: seata-account
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
  datasource:
    url: jdbc:mysql://124.71.187.82:3306/seata?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: caixin1997
    driver-class-name: com.mysql.jdbc.Driver

feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info


management:
  endpoints:
    web:
      exposure:
        include: "*"