server:
  port: 2002

spring:
  datasource:
    url: jdbc:mysql://124.71.187.82:3306/seata-storage?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: caixin1997
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
logging:
  level:
    io:
      seata: info
management:
  endpoints:
    web:
      exposure:
        include: "*"