server:
  port: 8191

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: shop-order


management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:mysql://${spring.cloud.nacos.discovery.ip}:3306/seata?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: caixin1997
    driver-class-name: com.mysql.jdbc.Driver

